server.port=${PORT:8080}
cors.allowedOrigins=${CORS_ALLOWED_ORIGINS:*}
server.desktop.sharedAuth=${SERVER_DESKTOP_SHARED_AUTH:}

# Avoid R2DBC autoconfig crash
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration,\
org.springframework.boot.autoconfigure.r2dbc.R2dbcDataAutoConfiguration,\
org.springframework.boot.autoconfigure.data.r2dbc.R2dbcRepositoriesAutoConfiguration
